x = 256

for x in range(x):
    print(";Enemy",str(x+1))
    print(";Enemy name")
    print("DB 165,198,199,194,214,205,213,175,206,198")
    print(";Growth rate")
    print(";y = mx + c where x = level")
    print(";Health")
    print(";m term")
    print("DB 01")
    print(";c term")
    print("DB 10")
    print(";Attack")
    print(";m term")
    print("DB 01")
    print(";c term")
    print("DB 10")
    print(";Defence")
    print(";m term")
    print("DB 01")
    print(";c term")
    print("DB 10")
    print(";MagicAttack")
    print(";m term")
    print("DB 01")
    print(";c term")
    print("DB 10")
    print(";MagicDefence")
    print(";m term")
    print("DB 01")
    print(";c term")
    print("DB 10")
    print(";Speed")
    print(";m term")
    print("DB 01")
    print(";c term")
    print("DB 10")
    print(";Moves they can learn")
    print("DB 0,0,0,0,0,0,0,0")
    print(";Encounter number")
    print("DB 0 ;Default encounter")
    print(";Memory reference for their tiles")
    print("DW Enemy{}Tiles".format(str(x+1)))
    print(";Gold gained from defeating this enemy:")
    print("DB 00")
    print(";Exp gained from defeating this enemy:")
    print("DB 00")
    print("")
